import { createAdministrationRoute } from './administration-route'

export const academicRoutes = [
  createAdministrationRoute({
    path: 'academic-years',
    name: 'academicYearsList',
    component: () => import('@/pages/admin-system/academic-years/AcademicYearsListPage.vue'),
    title: 'navigation.academicYears',
    permissions: ['academic_years.view'],
    order: 60,
  }),
  createAdministrationRoute({
    path: 'academic-years/create',
    name: 'academicYearCreate',
    component: () => import('@/pages/admin-system/academic-years/CreateAcademicYearPage.vue'),
    title: 'navigation.createAcademicYear',
    permissions: ['academic_years.view', 'academic_years.manage'],
  }),
  createAdministrationRoute({
    path: 'academic-years/:academicYearId',
    name: 'academicYearDetail',
    component: () => import('@/pages/admin-system/academic-years/AcademicYearDetailPage.vue'),
    title: 'navigation.academicYearDetail',
    permissions: ['academic_years.view'],
    returnListRoute: 'academicYearsList',
    mode: 'detail',
    resource: 'academicYears',
  }),
  createAdministrationRoute({
    path: 'academic-years/:academicYearId/edit',
    name: 'academicYearEdit',
    component: () => import('@/pages/admin-system/academic-years/EditAcademicYearPage.vue'),
    title: 'navigation.editAcademicYear',
    permissions: ['academic_years.view', 'academic_years.manage'],
    returnListRoute: 'academicYearsList',
    mode: 'edit',
    resource: 'academicYears',
  }),
  createAdministrationRoute({
    path: 'academic-periods',
    name: 'academicPeriodsList',
    component: () => import('@/pages/admin-system/academic-periods/AcademicPeriodsListPage.vue'),
    title: 'navigation.academicPeriods',
    permissions: ['academic_periods.view'],
    order: 70,
  }),
  createAdministrationRoute({
    path: 'academic-periods/create',
    name: 'academicPeriodCreate',
    component: () => import('@/pages/admin-system/academic-periods/CreateAcademicPeriodPage.vue'),
    title: 'navigation.createAcademicPeriod',
    permissions: ['academic_periods.view', 'academic_periods.manage', 'academic_years.view'],
  }),
  createAdministrationRoute({
    path: 'academic-periods/:academicPeriodId',
    name: 'academicPeriodDetail',
    component: () => import('@/pages/admin-system/academic-periods/AcademicPeriodDetailPage.vue'),
    title: 'navigation.academicPeriodDetail',
    permissions: ['academic_periods.view'],
    returnListRoute: 'academicPeriodsList',
    mode: 'detail',
    resource: 'academicPeriods',
  }),
  createAdministrationRoute({
    path: 'academic-periods/:academicPeriodId/edit',
    name: 'academicPeriodEdit',
    component: () => import('@/pages/admin-system/academic-periods/EditAcademicPeriodPage.vue'),
    title: 'navigation.editAcademicPeriod',
    permissions: ['academic_periods.view', 'academic_periods.manage'],
    returnListRoute: 'academicPeriodsList',
    mode: 'edit',
    resource: 'academicPeriods',
  }),
]
