import { createAdministrationRoute } from './administration-route'

export const accessAdministrationRoutes = [
  createAdministrationRoute({
    path: 'users',
    name: 'usersList',
    component: () => import('@/pages/admin-system/users/UsersListPage.vue'),
    title: 'navigation.users',
    permissions: ['users.view'],
    order: 30,
  }),
  createAdministrationRoute({
    path: 'users/create',
    name: 'userCreate',
    component: () => import('@/pages/admin-system/users/CreateUserPage.vue'),
    title: 'navigation.createUser',
    permissions: ['users.view', 'users.manage', 'roles.view'],
  }),
  createAdministrationRoute({
    path: 'users/:userId',
    name: 'userDetail',
    component: () => import('@/pages/admin-system/users/UserDetailPage.vue'),
    title: 'navigation.userDetail',
    permissions: ['users.view'],
    returnListRoute: 'usersList',
    mode: 'detail',
    resource: 'users',
  }),
  createAdministrationRoute({
    path: 'users/:userId/edit',
    name: 'userEdit',
    component: () => import('@/pages/admin-system/users/EditUserPage.vue'),
    title: 'navigation.editUser',
    permissions: ['users.view', 'users.manage', 'roles.view'],
    returnListRoute: 'usersList',
    mode: 'edit',
    resource: 'users',
  }),
  createAdministrationRoute({
    path: 'roles',
    name: 'rolesList',
    component: () => import('@/pages/admin-system/roles/RolesListPage.vue'),
    title: 'navigation.roles',
    permissions: ['roles.view'],
    order: 40,
  }),
  createAdministrationRoute({
    path: 'roles/create',
    name: 'roleCreate',
    component: () => import('@/pages/admin-system/roles/CreateRolePage.vue'),
    title: 'navigation.createRole',
    permissions: ['roles.view', 'roles.manage', 'permissions.view'],
  }),
  createAdministrationRoute({
    path: 'roles/:roleId',
    name: 'roleDetail',
    component: () => import('@/pages/admin-system/roles/RoleDetailPage.vue'),
    title: 'navigation.roleDetail',
    permissions: ['roles.view'],
    returnListRoute: 'rolesList',
    mode: 'detail',
    resource: 'roles',
  }),
  createAdministrationRoute({
    path: 'roles/:roleId/edit',
    name: 'roleEdit',
    component: () => import('@/pages/admin-system/roles/EditRolePage.vue'),
    title: 'navigation.editRole',
    permissions: ['roles.view', 'roles.manage', 'permissions.view'],
    returnListRoute: 'rolesList',
    mode: 'edit',
    resource: 'roles',
  }),
  createAdministrationRoute({
    path: 'permissions',
    name: 'permissionsList',
    component: () => import('@/pages/admin-system/permissions/PermissionsListPage.vue'),
    title: 'navigation.permissions',
    permissions: ['permissions.view'],
    order: 50,
  }),
]
