import { createAdministrationRoute } from './administration-route'

export const accessAdministrationRoutes = [
  createAdministrationRoute({
    path: 'students',
    name: 'studentProfilesList',
    component: () => import('@/pages/admin-system/students/StudentProfilesPage.vue'),
    title: 'studentEnrollmentRoster.students.title',
    permissions: ['student_profiles.view'],
    order: 20,
  }),
  createAdministrationRoute({
    path: 'students/create',
    name: 'studentProfileCreate',
    component: () => import('@/pages/admin-system/students/StudentProfileCreatePage.vue'),
    title: 'studentEnrollmentRoster.students.create',
    permissions: ['student_profiles.manage'],
  }),
  createAdministrationRoute({
    path: 'students/:studentProfileId',
    name: 'studentProfileDetail',
    component: () => import('@/pages/admin-system/students/StudentProfileDetailPage.vue'),
    title: 'studentEnrollmentRoster.students.detail',
    permissions: ['student_profiles.view'],
    returnListRoute: 'studentProfilesList',
    mode: 'detail',
    resource: 'studentProfiles',
  }),
  createAdministrationRoute({
    path: 'class-sections',
    name: 'classSectionsList',
    component: () => import('@/pages/admin-system/class-sections/ClassSectionsPage.vue'),
    title: 'studentEnrollmentRoster.classSections.title',
    permissions: ['class_sections.view'],
    order: 25,
  }),
  createAdministrationRoute({
    path: 'class-sections/create',
    name: 'classSectionCreate',
    component: () => import('@/pages/admin-system/class-sections/ClassSectionCreatePage.vue'),
    title: 'studentEnrollmentRoster.classSections.create',
    permissions: ['class_sections.manage'],
  }),
  createAdministrationRoute({
    path: 'class-sections/:classSectionId',
    name: 'classSectionDetail',
    component: () => import('@/pages/admin-system/class-sections/ClassSectionDetailPage.vue'),
    title: 'studentEnrollmentRoster.classSections.detail',
    permissions: ['class_sections.view'],
    returnListRoute: 'classSectionsList',
    mode: 'detail',
    resource: 'classSections',
  }),
  createAdministrationRoute({
    path: 'teacher-assignments',
    name: 'teacherAssignmentsList',
    component: () => import('@/pages/admin-system/teacher-assignments/TeacherAssignmentsPage.vue'),
    title: 'studentEnrollmentRoster.teacherAssignments.title',
    permissions: ['teacher_assignments.view'],
    order: 28,
  }),
  createAdministrationRoute({
    path: 'teacher-assignments/:teacherAssignmentId',
    name: 'teacherAssignmentDetail',
    component: () => import('@/pages/admin-system/teacher-assignments/TeacherAssignmentDetailPage.vue'),
    title: 'studentEnrollmentRoster.teacherAssignments.detail',
    permissions: ['teacher_assignments.view'],
    returnListRoute: 'teacherAssignmentsList',
    mode: 'detail',
    resource: 'teacherAssignments',
  }),
  createAdministrationRoute({
    path: 'users',
    name: 'usersList',
    component: () => import('@/pages/admin-system/users/UsersListPage.vue'),
    title: 'navigation.users',
    permissions: ['users.view'],
    order: 30,
  }),
  createAdministrationRoute({
    path: 'users/create',
    name: 'userCreate',
    component: () => import('@/pages/admin-system/users/CreateUserPage.vue'),
    title: 'navigation.createUser',
    permissions: ['users.view', 'users.manage', 'roles.view'],
  }),
  createAdministrationRoute({
    path: 'users/:userId',
    name: 'userDetail',
    component: () => import('@/pages/admin-system/users/UserDetailPage.vue'),
    title: 'navigation.userDetail',
    permissions: ['users.view'],
    returnListRoute: 'usersList',
    mode: 'detail',
    resource: 'users',
  }),
  createAdministrationRoute({
    path: 'users/:userId/edit',
    name: 'userEdit',
    component: () => import('@/pages/admin-system/users/EditUserPage.vue'),
    title: 'navigation.editUser',
    permissions: ['users.view', 'users.manage', 'roles.view'],
    returnListRoute: 'usersList',
    mode: 'edit',
    resource: 'users',
  }),
  createAdministrationRoute({
    path: 'roles',
    name: 'rolesList',
    component: () => import('@/pages/admin-system/roles/RolesListPage.vue'),
    title: 'navigation.roles',
    permissions: ['roles.view'],
    order: 40,
  }),
  createAdministrationRoute({
    path: 'roles/create',
    name: 'roleCreate',
    component: () => import('@/pages/admin-system/roles/CreateRolePage.vue'),
    title: 'navigation.createRole',
    permissions: ['roles.view', 'roles.manage', 'permissions.view'],
  }),
  createAdministrationRoute({
    path: 'roles/:roleId',
    name: 'roleDetail',
    component: () => import('@/pages/admin-system/roles/RoleDetailPage.vue'),
    title: 'navigation.roleDetail',
    permissions: ['roles.view'],
    returnListRoute: 'rolesList',
    mode: 'detail',
    resource: 'roles',
  }),
  createAdministrationRoute({
    path: 'roles/:roleId/edit',
    name: 'roleEdit',
    component: () => import('@/pages/admin-system/roles/EditRolePage.vue'),
    title: 'navigation.editRole',
    permissions: ['roles.view', 'roles.manage', 'permissions.view'],
    returnListRoute: 'rolesList',
    mode: 'edit',
    resource: 'roles',
  }),
  createAdministrationRoute({
    path: 'permissions',
    name: 'permissionsList',
    component: () => import('@/pages/admin-system/permissions/PermissionsListPage.vue'),
    title: 'navigation.permissions',
    permissions: ['permissions.view'],
    order: 50,
  }),
]
